### ISSUE TITLE
[BUG] Docker version missing `tkinter` dependency. 

### ISSUE THREAD

**Issue by filbe1** [CBICA/NiChart_Project#22]
### **Describe the bug**
I tried running the docker image provided on the docker hub: `cbica/nichart`. I ran into one minor inconvenience and an actual bug.
The inconvenience was that the `latest` tag wasn't added to the images so pulling the image like `docker pull cbica/nichart` results in this error: `Error response from daemon: manifest for cbica/nichart:latest not found: manifest unknown: manifest unknown`

Now this isn't the end of the word but I thought I will mention it, if I'M already writing a bug report.

The actual bug is that `tkinter` is missing from the docker image so most of the tools cannot start.
Also the `libx11-6 libx11-dev` packages are missing too. tkinter builds upon these so it might be that you tried to install it but it failed silently.

### **To Reproduce**
```@bash
$ docker pull cbica/nichart:0.0.1 # Need to provide the tag
$ docker run cbica/nichart:0.0.1
```

### **Expected behavior**
I was expecting to see the tools work, so I can start learning them.

### **Screenshots**
Screenshot of the error:
![Screenshot from 2024-10-03 10-13-00](https://github.com/user-attachments/assets/e421155f-a501-4d36-831d-4a1b2d56e419)

### **Platform Info (please complete the following information):**
 - I'm using ubuntu 22.04, with docker: `Docker version 27.3.1, build ce12230`

### **Additional context**
I checked the build of the docker file and it is rarely a good idea to copy a whole pre-built conda, or anything pre-built for that matter to the image. It is more secure if one installs conda directly inside or inherits from a container that has conda built already.

**Comment by spirosmaggioros** [comment]
@filbe1 Thank you for your feedback, we are sorry for the discomfort and i want to let you know that this repo is under heavy development right now and it's not yet stable(it won't be long until we have a very stable version). 
I don't work on the docker version but i assume what you said it's true, it seems like tkinter is missing from the docker image. We will fix this shortly. Thank you once again!

**Comment by filbe1** [comment]
Thanks for the quick reply. I tried installing the toolkit as per the main `Readme.md`-s instructions, however some of the submodules require identification, most likely they are not public repositories or something along those lines. The repo I had issue with is: `fMRI/pNet`. 
The full error:
```@bash
fatal: Authentication failed for 'https://github.com/CBICA/pNet/'
fatal: clone of 'https://github.com/CBICA/pNet' into submodule path '/home/...../NiChart_Project/src/Image_Processing/fMRI/pNet' failed
Failed to clone 'src/Image_Processing/fMRI/pNet' a second time, aborting
```

**Comment by spirosmaggioros** [comment]
Yes, the repos are there for educational purposes and we don't directly use them, i will change the README today and update it with the new instructions.
This repo implements the viewer that it's basically the whole project, for third party tools we use our PyPI packages, please give me some time and this will be fixed. Thank you!

**Comment by spirosmaggioros** [comment]
@filbe1 Please try this:
- ```bash pip install -r requirements.txt```
- ```bash cd src/NiChart_Viewer/src/ && streamlit run NiChartProject.py```

Tell me if this works for you, please re-clone it or fetch the new changes. You *only* have to install the requirements as of now.

**Comment by AlexanderGetka-cbica** [comment]
Not sure why tkinter was never added to the requirements, we will fix this shortly.

Currently the docker build is experimental, so no `latest` tag was pushed to prevent an automatic pull. Once we are in a more stable state we'll push the default torch/cuda/cudnn versions 

> I checked the build of the docker file and it is rarely a good idea to copy a whole pre-built conda, or anything pre-built for that matter to the image. It is more secure if one installs conda directly inside or inherits from a container that has conda built already.

We aren't copying in the environment this way, we are copying in the source repo and  installing using the pip local install mechanism.

**Comment by filbe1** [comment]
Oh sorry for butting in with the docker comment then, it seemed so suspicious. The install works fine with the new instructions thank you.

**Comment by spirosmaggioros** [comment]
This issue will be closed, if there are any more issues it will be re-opened.
