### ISSUE TITLE
Providing users options to work on subset of variables (specifically in visualizations)

### ISSUE THREAD

**Issue by gurayerus** [CBICA/NiChart_Project#31]
We have too many variables (>100 ROIs, and additional ones from SPARE, etc). Its' difficult for the user to even select from such a long list

We provide a selector (may be in a separate "settings" panel/tab) to the user to select the set of variables they want to use. The selection will use a dictionary with variable types to group them in meaningful batches (potentially with overlapping elements). For example "all ROIs", "primary ROIs (a set of major regions)", "SPARE scores", etc

**Comment by AlexanderGetka-cbica** [comment]
We could use multiple tiers of selectbox. For example, first selectbox selects a batch. On update, this batch is used to populate the second selectbox. This second selectbox selects the individual feature.
