### ISSUE TITLE
[BUG] Error while running DLWMLS in the demo

### ISSUE THREAD

**Issue by pjsjongsung** [CBICA/NiChart_Project#74]
### **Describe the bug**
DLWMLS section throws an error in the demo

### **To Reproduce**
1. Go to WM Lesion segmentation demo
2. Click on DLWMLS

### **Expected behavior**
Give some indication of DLWMLS running

### **Screenshots**
![image](https://github.com/user-attachments/assets/6510eca4-bb36-48b8-a256-24c6062fef80)

### **Platform Info (please complete the following information):**
Cloud demo

**Comment by gurayerus** [comment]
This was due to a bug with the initialization of the state variable. It'sa now fixed. Upload to cloud may not be immediate.
